---
resolver: lts-12.10

extra-deps:
  - hspec-megaparsec-2.1.0
  - hspec-expectations-0.8.2
  - hspec-2.5.6
  - hspec-core-2.5.6
  - hspec-discover-2.5.6
  - parser-combinators-1.0.0
  - HUnit-1.6.0.0
  - QuickCheck-2.12.2
  - quickcheck-io-0.2.0
  - megaparsec-8.0.0
